Fix DivideOp: change resulting type to float64
antonmedv/expr pull request #272
Opened 2022-11-04 18:57 UTC by Dentrax

Fixes #270

Signed-off-by: Furkan <furkan.turkal@trendyol.com>

Added all possible `/` tests for different types, and it's working as expected now. Also I had to add `runtime.ToFloat64()` for `OpDivide`, otherwise it rounds up the value and converts `float32`. For example:

```diff
- float32(0.96039605)
+ float64(0.9603960514068604)
```

`-` is wrong, `+` is correct value (with `runtime.ToFloat64`).

cc @antonmedv

2022-11-04 19:18 UTC, antonmedv commented
Nice. But please update generator of helpers.

2022-11-04 19:33 UTC, Dentrax commented
Ah, sure boss! Didn't notice it! Now it's done.

2022-11-04 21:12 UTC, antonmedv requested changes

2022-11-04 21:12 UTC, antonmedv commented on vm/vm.go
> +			vm.push(runtime.ToFloat64(runtime.Divide(a, b)))
ToFloat64 not needed here.

2022-11-04 21:26 UTC, Dentrax commented on expr_test.go
> +		{"int8 / int16", 0.3333333333333333},
Makes sense, done!

2022-11-04 21:40 UTC, antonmedv approved these changes

2022-11-05 12:47 UTC, antonmedv commented
Gonna fix tests on my own.

2022-11-05 12:47 UTC, merged