feat: Add context.Context support for methods and functions
antonmedv/expr pull request #381
Opened 2023-06-08 12:30 UTC by thomascoquet

Idea is to support functions of the form `func(context.Context, any...) (any, error)` (c.f. https://github.com/antonmedv/expr/issues/380).

Changes are lightweight: 

- A new OpCode is introduced for `builtin.Function` having `context.Context` as first argument,
- This setting can be set using `&builtin.Function{Context: true}`,
- For methods, type check was modified to account for such kinds of method and the runtime was updated accordingly.

The use cases include:

- doing interruptable work with `expr`  (requests, etc.),
- my personal use case is keeping track of created objects, using the context as a poor man's DI.

Alternatives using methods:
```go
type env struct{
    context.Context
}

func (e *env) Do(s string) string {
    return s
}
```
lacks the type flexibility provided by `builtin.Function`.

2023-06-20 11:24 UTC, antonmedv requested changes

2023-06-20 11:24 UTC, antonmedv commented on builtin/builtin.go
> +	Context bool
Let's add a new field, instead of this `Context` field. 

    FuncWithContext func(ctx, args ...interface{}) (interface{}, error)

2023-06-20 11:24 UTC, antonmedv commented on docs/Getting-Started.md
> +		func(params ...any) (any, error) {
Same here, the expr.FunctionWithContext can be with signature of

    func (ctx, params...) any, error

2023-06-20 11:24 UTC, antonmedv commented on expr_test.go
> +			for _, each := range p[1:] {
Let's also add the test of what actually uses the context feature. Something with terminating.

2023-06-20 11:24 UTC, antonmedv commented on vm/vm.go
> +	vm := VM{ctx: ctx}
Currently, vm doesn't do anything with context. Only passed to some functions. 

But **expr.RunWithContext** sounds like VM should be stopped (for example on deadline).

2023-06-20 11:24 UTC, antonmedv commented on vm/vm.go
> +			if fnt.NumIn() > 0 && fn.Type().In(0) == contextType {
Let's not introduce context passing for general OpCall. 

Let's allow context to be passed only to funcs defined via `expr.FunctionWithContext` in OpCallContext.

2023-06-20 11:24 UTC, antonmedv commented
Overall a good PR. I have a few comments.

2023-06-28 17:49 UTC, thomascoquet commented
Hello Anton,
I applied the requested changes. I chose to use a wrapper to use the same func slice in `*vm.Program` instead of duplicating it.
Thomas

2023-08-12 14:03 UTC, antonmedv commented
Now ai think why do we need to pass context to functions via expr.VM. 

This passing of context complicates vm arguments handling. 

The VM itself doesn’t need context as I understand right now. 

Maybe there’s better methods of passing context to user defined functions?

2023-08-12 15:34 UTC, antonmedv commented
Or we can implement this via our own custom patcher. I think this is the right solution.

2023-08-14 09:54 UTC, antonmedv commented
### Added a doc on how to add context via patcher. 

- https://github.com/antonmedv/expr/blob/master/docs/Visitor-and-Patch.md#patch

2023-08-14 09:54 UTC, closed without merging

2023-11-27 20:58 UTC, antonmedv commented
FYI. I've implemented my own version of context patcher and added a config option https://github.com/antonmedv/expr/blob/f92bb7949de064a05d5b3a61d1b07abef0c521bb/expr.go#L157-L161

```go
func ExampleWithContext() {
	env := map[string]any{
		"fn": func(ctx context.Context, _, _ int) int {
			// An infinite loop that can be canceled by context.
			for {
				select {
				case <-ctx.Done():
					return 42
				}
			}
		},
		"ctx": context.TODO(), // Context should be passed as a variable.
	}

	program, err := expr.Compile(`fn(1, 2)`,
		expr.Env(env),
		expr.WithContext("ctx"), // Pass context variable name.
	)
	if err != nil {
		fmt.Printf("%v", err)
		return
	}

	// Cancel context after 100 milliseconds.
	ctx, cancel := context.WithTimeout(context.Background(), time.Millisecond*100)
	defer cancel()

	// After program is compiled, context can be passed to Run.
	env["ctx"] = ctx

	// Run will return 42 after 100 milliseconds.
	output, err := expr.Run(program, env)
	if err != nil {
		fmt.Printf("%v", err)
		return
	}

	fmt.Printf("%v", output)
	// Output: 42
}
```